baseURL = "https://keanyaphelps.com/"
languageCode = "en-us"
title = "Keanya Phelps"
theme = "PaperMod"

[params]
  author = "Keanya Phelps"
  description = "Welcome to my personal website"
  keywords = ["blog", "portfolio", "personal"]

  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "I help teams do their best work."
    Content = "Former Python/Django dev with 5+ years managing web and data projectsâ€”clear scope, steady cadence, measurable impact."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/KeanyaPhelps"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/KeanyaPhelps"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/keanyaphelps/"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
